DATASET:
  DATA_ROOT: "/workspace/AI_model/data"
  TRAIN:
    IMG_PREFIX: "03_syn_word_video"
    ANN_FILE: "03_syn_word_annotations.csv"
    KEYPOINT_PREFIX: "03_syn_word_keypoint"
  VAL:
    IMG_PREFIX: "03_syn_word_video"
    ANN_FILE: "03_syn_word_annotations.csv"
    KEYPOINT_PREFIX: "03_syn_word_keypoint"
  WORKER_PER_GPU: 8

  TRANSFORM:
    RESIZE_IMG: (256, 256)
    TEMPORAL_SCALING: 1.0
    CROP_SIZE: (224, 224)
    TEMPORAL_CROP_RATIO: 0.0
    MEAN: (0.0637, 0.0988, 0.2312)
    STD: (0.0643, 0.0556, 0.1150)
  VOCABULARY:
    EXCLUDE_TOKENS:
      - __ON__  #not used in ksl
      - __OFF__

SOLVER:
  BATCH_PER_GPU: 2
  BIAS_LR_FACTOR: 1.0
  RAMPDOWN_ITERS: 0
  BASE_LR: 1e-3
  OPTIM_NAME: "AdamW"
  SGD:
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0005
    NESTEROV: true
  ADAM:
    BETA1: 0.9
    BETA2: 0.999
    EPS: 1.0e-08
    WEIGHT_DECAY: 1e-4

  LR_SCHEDULER_NAME: "ReduceLROnPlateau"
  STEPS: (40, 60,)
  GAMMA: 0.5
  RAMPDOWN_ITERS: 0
  WARMUP_FACTOR: 1
  WARMUP_ITERS: 500
  WARMUP_METHOD: "linear"
PERIODS:
  EVAL: 1
  CHECKPOINT: 1
  LOG_ITERS: 300
OUTPUT_DIR: outputs/segment_ksl
RESUME: ""
GPU_ID: 0
NOTE: ""

SEED: 42
CUDNN_BENCHMARK: False
CUDNN_DETERMINISTIC: True