defaults:
  - _self_

# Test Configuration for MSKA Model Training

model:
  name: "MSKA_Model"
  input_dim: 274
  d_model: 512
  nhead: 4
  num_encoder_layers: 4
  num_decoder_layers: 4
  dim_feedforward: 1024
  dropout: 0.2

dataset:
  data_root: "./data"
  
  # Dataset size configuration
  train_size: null  # null for full dataset, integer for subset
  val_size: null
  test_size: null
  
  # Data loading
  batch_size: 1
  num_workers: 0
  persistent_workers: false
  pin_memory: false
  
  # Dataset splitting configuration
  auto_split: false  # Automatically split train data if val not found
  split_ratios:
    train: 1.0
    val: 0.0
  min_vocab_count: 1
  
  # Direction filtering
  directions: ["F", "L", "R", "U", "D"]
  include_directions: null  # null for all, list for specific directions
  
  # Data directories structure
  train:
    morpheme_dir: "train/morpheme"
    keypoint_dir: "train/keypoint"
  val:
    morpheme_dir: "val/morpheme"
    keypoint_dir: "val/keypoint"
  test:
    morpheme_dir: "test/morpheme"
    keypoint_dir: "test/keypoint"

# Additional settings
use_test: false  # Whether to use test split if available
extract_from_video: false  # Whether to extract keypoints from video if needed

training:
  epochs: 100
  learning_rate: 1e-4
  weight_decay: 1e-4
  grad_clip_norm: 2.0
  
loss:
  type: "eos_enhanced"
  eos_weight: 3.0

scheduler:
  name: "ReduceLROnPlateau"
  mode: "min"
  factor: 0.5
  patience: 2

output:
  dir: "./test_outputs"
  save_best: true
  save_every_n_epochs: 1
  
device:
  use_cuda: false
  gpu_id: 0

preprocessing:
  hand_scale: 1.5
  normalize_center: true
  shoulder_width_scale: true
  hand_emphasis: true
  cache_preprocessed: true
  cache_dir: "./cache"

keypoint_extraction:
  openpose_model_path: "/Users/user/Desktop/openpose/models"  # Path to OpenPose models directory
  confidence_threshold: 0.5
  method: "openpose"  # Options: "openpose", "mediapipe"


vocab:
  save_path: "vocabulary.json"
  expandable: true
  force_rebuild: false

# Experiment tracking
experiment:
  name: "mska_test"
  version: "v1.0"
  tags: ["sign_language", "transformer", "mska", "test"]
  
# Data types and sources
data_types:
  studio:
    description: "Carefully-created studio data with 5 cameras (F,L,R,U,D)"
    quality: "high"
    directions: ["F", "L", "R", "U", "D"]
  crowd_sourcing:
    description: "Crowd-sourced data with only Front direction"
    quality: "medium"
    directions: ["F"]
  synthetic:
    description: "Synthetic data with same directions as studio"
    quality: "synthetic"
    directions: ["F", "L", "R", "U", "D"]